// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/mavenlink-communicator/mavenlink-communicator.proto

package costrategix_service_mavenlink_communicator

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Project struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AccessLevel          string   `protobuf:"bytes,4,opt,name=accessLevel,proto3" json:"accessLevel,omitempty"`
	AccountId            int32    `protobuf:"varint,5,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Archived             bool     `protobuf:"varint,6,opt,name=archived,proto3" json:"archived,omitempty"`
	Currency             string   `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	CurrencySymbol       string   `protobuf:"bytes,8,opt,name=currencySymbol,proto3" json:"currencySymbol,omitempty"`
	DueDate              string   `protobuf:"bytes,9,opt,name=dueDate,proto3" json:"dueDate,omitempty"`
	EffectiveDueDate     string   `protobuf:"bytes,10,opt,name=effectiveDueDate,proto3" json:"effectiveDueDate,omitempty"`
	StartDate            string   `protobuf:"bytes,11,opt,name=startDate,proto3" json:"startDate,omitempty"`
	CreatedAt            string   `protobuf:"bytes,12,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,13,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_mavenlink_communicator_a9af29e9786aea96, []int{0}
}
func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (dst *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(dst, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Project) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Project) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Project) GetAccessLevel() string {
	if m != nil {
		return m.AccessLevel
	}
	return ""
}

func (m *Project) GetAccountId() int32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *Project) GetArchived() bool {
	if m != nil {
		return m.Archived
	}
	return false
}

func (m *Project) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Project) GetCurrencySymbol() string {
	if m != nil {
		return m.CurrencySymbol
	}
	return ""
}

func (m *Project) GetDueDate() string {
	if m != nil {
		return m.DueDate
	}
	return ""
}

func (m *Project) GetEffectiveDueDate() string {
	if m != nil {
		return m.EffectiveDueDate
	}
	return ""
}

func (m *Project) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *Project) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Project) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type Task struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StoryType            string   `protobuf:"bytes,4,opt,name=story_type,json=storyType,proto3" json:"story_type,omitempty"`
	Priority             string   `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Archived             bool     `protobuf:"varint,6,opt,name=archived,proto3" json:"archived,omitempty"`
	WorkspaceId          string   `protobuf:"bytes,7,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	CreatorId            string   `protobuf:"bytes,8,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	ParentId             string   `protobuf:"bytes,9,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	DueDate              string   `protobuf:"bytes,10,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	State                string   `protobuf:"bytes,11,opt,name=state,proto3" json:"state,omitempty"`
	StartDate            string   `protobuf:"bytes,12,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	CreatedAt            string   `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	User                 *User    `protobuf:"bytes,15,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_mavenlink_communicator_a9af29e9786aea96, []int{1}
}
func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (dst *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(dst, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Task) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Task) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Task) GetStoryType() string {
	if m != nil {
		return m.StoryType
	}
	return ""
}

func (m *Task) GetPriority() string {
	if m != nil {
		return m.Priority
	}
	return ""
}

func (m *Task) GetArchived() bool {
	if m != nil {
		return m.Archived
	}
	return false
}

func (m *Task) GetWorkspaceId() string {
	if m != nil {
		return m.WorkspaceId
	}
	return ""
}

func (m *Task) GetCreatorId() string {
	if m != nil {
		return m.CreatorId
	}
	return ""
}

func (m *Task) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *Task) GetDueDate() string {
	if m != nil {
		return m.DueDate
	}
	return ""
}

func (m *Task) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Task) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *Task) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Task) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Task) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type Timeentry struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DatePerformed        string   `protobuf:"bytes,2,opt,name=date_performed,json=datePerformed,proto3" json:"date_performed,omitempty"`
	TimeInMinutes        int32    `protobuf:"varint,3,opt,name=time_in_minutes,json=timeInMinutes,proto3" json:"time_in_minutes,omitempty"`
	Notes                string   `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	WorkspaceId          string   `protobuf:"bytes,5,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	StoryId              string   `protobuf:"bytes,6,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	CreatedAt            string   `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	User                 *User    `protobuf:"bytes,9,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timeentry) Reset()         { *m = Timeentry{} }
func (m *Timeentry) String() string { return proto.CompactTextString(m) }
func (*Timeentry) ProtoMessage()    {}
func (*Timeentry) Descriptor() ([]byte, []int) {
	return fileDescriptor_mavenlink_communicator_a9af29e9786aea96, []int{2}
}
func (m *Timeentry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timeentry.Unmarshal(m, b)
}
func (m *Timeentry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timeentry.Marshal(b, m, deterministic)
}
func (dst *Timeentry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timeentry.Merge(dst, src)
}
func (m *Timeentry) XXX_Size() int {
	return xxx_messageInfo_Timeentry.Size(m)
}
func (m *Timeentry) XXX_DiscardUnknown() {
	xxx_messageInfo_Timeentry.DiscardUnknown(m)
}

var xxx_messageInfo_Timeentry proto.InternalMessageInfo

func (m *Timeentry) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Timeentry) GetDatePerformed() string {
	if m != nil {
		return m.DatePerformed
	}
	return ""
}

func (m *Timeentry) GetTimeInMinutes() int32 {
	if m != nil {
		return m.TimeInMinutes
	}
	return 0
}

func (m *Timeentry) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *Timeentry) GetWorkspaceId() string {
	if m != nil {
		return m.WorkspaceId
	}
	return ""
}

func (m *Timeentry) GetStoryId() string {
	if m != nil {
		return m.StoryId
	}
	return ""
}

func (m *Timeentry) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Timeentry) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Timeentry) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	EmailAddress         string   `protobuf:"bytes,3,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	Headline             string   `protobuf:"bytes,4,opt,name=headline,proto3" json:"headline,omitempty"`
	AccountId            string   `protobuf:"bytes,5,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_mavenlink_communicator_a9af29e9786aea96, []int{3}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *User) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *User) GetHeadline() string {
	if m != nil {
		return m.Headline
	}
	return ""
}

func (m *User) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type MavenlinkResponseResults struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MavenlinkResponseResults) Reset()         { *m = MavenlinkResponseResults{} }
func (m *MavenlinkResponseResults) String() string { return proto.CompactTextString(m) }
func (*MavenlinkResponseResults) ProtoMessage()    {}
func (*MavenlinkResponseResults) Descriptor() ([]byte, []int) {
	return fileDescriptor_mavenlink_communicator_a9af29e9786aea96, []int{4}
}
func (m *MavenlinkResponseResults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MavenlinkResponseResults.Unmarshal(m, b)
}
func (m *MavenlinkResponseResults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MavenlinkResponseResults.Marshal(b, m, deterministic)
}
func (dst *MavenlinkResponseResults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MavenlinkResponseResults.Merge(dst, src)
}
func (m *MavenlinkResponseResults) XXX_Size() int {
	return xxx_messageInfo_MavenlinkResponseResults.Size(m)
}
func (m *MavenlinkResponseResults) XXX_DiscardUnknown() {
	xxx_messageInfo_MavenlinkResponseResults.DiscardUnknown(m)
}

var xxx_messageInfo_MavenlinkResponseResults proto.InternalMessageInfo

func (m *MavenlinkResponseResults) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MavenlinkResponseResults) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MavenlinkWorkspace struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AccessLevel          string   `protobuf:"bytes,4,opt,name=access_level,json=accessLevel,proto3" json:"access_level,omitempty"`
	AccountId            int32    `protobuf:"varint,5,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Archived             bool     `protobuf:"varint,6,opt,name=archived,proto3" json:"archived,omitempty"`
	Currency             string   `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	CurrencySymbol       string   `protobuf:"bytes,8,opt,name=currency_symbol,json=currencySymbol,proto3" json:"currency_symbol,omitempty"`
	DueDate              string   `protobuf:"bytes,9,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	EffectiveDueDate     string   `protobuf:"bytes,10,opt,name=effective_due_date,json=effectiveDueDate,proto3" json:"effective_due_date,omitempty"`
	StartDate            string   `protobuf:"bytes,11,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	CreatedAt            string   `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MavenlinkWorkspace) Reset()         { *m = MavenlinkWorkspace{} }
func (m *MavenlinkWorkspace) String() string { return proto.CompactTextString(m) }
func (*MavenlinkWorkspace) ProtoMessage()    {}
func (*MavenlinkWorkspace) Descriptor() ([]byte, []int) {
	return fileDescriptor_mavenlink_communicator_a9af29e9786aea96, []int{5}
}
func (m *MavenlinkWorkspace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MavenlinkWorkspace.Unmarshal(m, b)
}
func (m *MavenlinkWorkspace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MavenlinkWorkspace.Marshal(b, m, deterministic)
}
func (dst *MavenlinkWorkspace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MavenlinkWorkspace.Merge(dst, src)
}
func (m *MavenlinkWorkspace) XXX_Size() int {
	return xxx_messageInfo_MavenlinkWorkspace.Size(m)
}
func (m *MavenlinkWorkspace) XXX_DiscardUnknown() {
	xxx_messageInfo_MavenlinkWorkspace.DiscardUnknown(m)
}

var xxx_messageInfo_MavenlinkWorkspace proto.InternalMessageInfo

func (m *MavenlinkWorkspace) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MavenlinkWorkspace) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MavenlinkWorkspace) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MavenlinkWorkspace) GetAccessLevel() string {
	if m != nil {
		return m.AccessLevel
	}
	return ""
}

func (m *MavenlinkWorkspace) GetAccountId() int32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *MavenlinkWorkspace) GetArchived() bool {
	if m != nil {
		return m.Archived
	}
	return false
}

func (m *MavenlinkWorkspace) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *MavenlinkWorkspace) GetCurrencySymbol() string {
	if m != nil {
		return m.CurrencySymbol
	}
	return ""
}

func (m *MavenlinkWorkspace) GetDueDate() string {
	if m != nil {
		return m.DueDate
	}
	return ""
}

func (m *MavenlinkWorkspace) GetEffectiveDueDate() string {
	if m != nil {
		return m.EffectiveDueDate
	}
	return ""
}

func (m *MavenlinkWorkspace) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *MavenlinkWorkspace) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *MavenlinkWorkspace) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type MavenlinkStory struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StoryType            string   `protobuf:"bytes,4,opt,name=story_type,json=storyType,proto3" json:"story_type,omitempty"`
	Priority             string   `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Archived             bool     `protobuf:"varint,6,opt,name=archived,proto3" json:"archived,omitempty"`
	WorkspaceId          string   `protobuf:"bytes,7,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	CreatorId            string   `protobuf:"bytes,8,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	ParentId             string   `protobuf:"bytes,9,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	DueDate              string   `protobuf:"bytes,10,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	State                string   `protobuf:"bytes,11,opt,name=state,proto3" json:"state,omitempty"`
	StartDate            string   `protobuf:"bytes,12,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	CreatedAt            string   `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	AssigneeIds          []string `protobuf:"bytes,15,rep,name=assignee_ids,json=assigneeIds,proto3" json:"assignee_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MavenlinkStory) Reset()         { *m = MavenlinkStory{} }
func (m *MavenlinkStory) String() string { return proto.CompactTextString(m) }
func (*MavenlinkStory) ProtoMessage()    {}
func (*MavenlinkStory) Descriptor() ([]byte, []int) {
	return fileDescriptor_mavenlink_communicator_a9af29e9786aea96, []int{6}
}
func (m *MavenlinkStory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MavenlinkStory.Unmarshal(m, b)
}
func (m *MavenlinkStory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MavenlinkStory.Marshal(b, m, deterministic)
}
func (dst *MavenlinkStory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MavenlinkStory.Merge(dst, src)
}
func (m *MavenlinkStory) XXX_Size() int {
	return xxx_messageInfo_MavenlinkStory.Size(m)
}
func (m *MavenlinkStory) XXX_DiscardUnknown() {
	xxx_messageInfo_MavenlinkStory.DiscardUnknown(m)
}

var xxx_messageInfo_MavenlinkStory proto.InternalMessageInfo

func (m *MavenlinkStory) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MavenlinkStory) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MavenlinkStory) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MavenlinkStory) GetStoryType() string {
	if m != nil {
		return m.StoryType
	}
	return ""
}

func (m *MavenlinkStory) GetPriority() string {
	if m != nil {
		return m.Priority
	}
	return ""
}

func (m *MavenlinkStory) GetArchived() bool {
	if m != nil {
		return m.Archived
	}
	return false
}

func (m *MavenlinkStory) GetWorkspaceId() string {
	if m != nil {
		return m.WorkspaceId
	}
	return ""
}

func (m *MavenlinkStory) GetCreatorId() string {
	if m != nil {
		return m.CreatorId
	}
	return ""
}

func (m *MavenlinkStory) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *MavenlinkStory) GetDueDate() string {
	if m != nil {
		return m.DueDate
	}
	return ""
}

func (m *MavenlinkStory) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *MavenlinkStory) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *MavenlinkStory) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *MavenlinkStory) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *MavenlinkStory) GetAssigneeIds() []string {
	if m != nil {
		return m.AssigneeIds
	}
	return nil
}

type MavenlinkTimeentry struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DatePerformed        string   `protobuf:"bytes,2,opt,name=date_performed,json=datePerformed,proto3" json:"date_performed,omitempty"`
	TimeInMinutes        int32    `protobuf:"varint,3,opt,name=time_in_minutes,json=timeInMinutes,proto3" json:"time_in_minutes,omitempty"`
	RateInCents          int32    `protobuf:"varint,4,opt,name=rate_in_cents,json=rateInCents,proto3" json:"rate_in_cents,omitempty"`
	Notes                string   `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	Billable             bool     `protobuf:"varint,6,opt,name=billable,proto3" json:"billable,omitempty"`
	WorkspaceId          string   `protobuf:"bytes,7,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	StoryId              string   `protobuf:"bytes,8,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	Currency             string   `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	CurrencyBaseUnit     int32    `protobuf:"varint,10,opt,name=currency_base_unit,json=currencyBaseUnit,proto3" json:"currency_base_unit,omitempty"`
	UserCanEdit          bool     `protobuf:"varint,11,opt,name=user_can_edit,json=userCanEdit,proto3" json:"user_can_edit,omitempty"`
	Approved             bool     `protobuf:"varint,12,opt,name=approved,proto3" json:"approved,omitempty"`
	UserId               string   `protobuf:"bytes,13,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt            string   `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MavenlinkTimeentry) Reset()         { *m = MavenlinkTimeentry{} }
func (m *MavenlinkTimeentry) String() string { return proto.CompactTextString(m) }
func (*MavenlinkTimeentry) ProtoMessage()    {}
func (*MavenlinkTimeentry) Descriptor() ([]byte, []int) {
	return fileDescriptor_mavenlink_communicator_a9af29e9786aea96, []int{7}
}
func (m *MavenlinkTimeentry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MavenlinkTimeentry.Unmarshal(m, b)
}
func (m *MavenlinkTimeentry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MavenlinkTimeentry.Marshal(b, m, deterministic)
}
func (dst *MavenlinkTimeentry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MavenlinkTimeentry.Merge(dst, src)
}
func (m *MavenlinkTimeentry) XXX_Size() int {
	return xxx_messageInfo_MavenlinkTimeentry.Size(m)
}
func (m *MavenlinkTimeentry) XXX_DiscardUnknown() {
	xxx_messageInfo_MavenlinkTimeentry.DiscardUnknown(m)
}

var xxx_messageInfo_MavenlinkTimeentry proto.InternalMessageInfo

func (m *MavenlinkTimeentry) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MavenlinkTimeentry) GetDatePerformed() string {
	if m != nil {
		return m.DatePerformed
	}
	return ""
}

func (m *MavenlinkTimeentry) GetTimeInMinutes() int32 {
	if m != nil {
		return m.TimeInMinutes
	}
	return 0
}

func (m *MavenlinkTimeentry) GetRateInCents() int32 {
	if m != nil {
		return m.RateInCents
	}
	return 0
}

func (m *MavenlinkTimeentry) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *MavenlinkTimeentry) GetBillable() bool {
	if m != nil {
		return m.Billable
	}
	return false
}

func (m *MavenlinkTimeentry) GetWorkspaceId() string {
	if m != nil {
		return m.WorkspaceId
	}
	return ""
}

func (m *MavenlinkTimeentry) GetStoryId() string {
	if m != nil {
		return m.StoryId
	}
	return ""
}

func (m *MavenlinkTimeentry) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *MavenlinkTimeentry) GetCurrencyBaseUnit() int32 {
	if m != nil {
		return m.CurrencyBaseUnit
	}
	return 0
}

func (m *MavenlinkTimeentry) GetUserCanEdit() bool {
	if m != nil {
		return m.UserCanEdit
	}
	return false
}

func (m *MavenlinkTimeentry) GetApproved() bool {
	if m != nil {
		return m.Approved
	}
	return false
}

func (m *MavenlinkTimeentry) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *MavenlinkTimeentry) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *MavenlinkTimeentry) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type MavenlinkUser struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	PhotoPath            string   `protobuf:"bytes,3,opt,name=photo_path,json=photoPath,proto3" json:"photo_path,omitempty"`
	EmailAddress         string   `protobuf:"bytes,4,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	Headline             string   `protobuf:"bytes,5,opt,name=headline,proto3" json:"headline,omitempty"`
	Generic              bool     `protobuf:"varint,6,opt,name=generic,proto3" json:"generic,omitempty"`
	Disabled             bool     `protobuf:"varint,7,opt,name=disabled,proto3" json:"disabled,omitempty"`
	UpdateWhitelist      []string `protobuf:"bytes,8,rep,name=update_whitelist,json=updateWhitelist,proto3" json:"update_whitelist,omitempty"`
	AccountId            string   `protobuf:"bytes,9,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MavenlinkUser) Reset()         { *m = MavenlinkUser{} }
func (m *MavenlinkUser) String() string { return proto.CompactTextString(m) }
func (*MavenlinkUser) ProtoMessage()    {}
func (*MavenlinkUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_mavenlink_communicator_a9af29e9786aea96, []int{8}
}
func (m *MavenlinkUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MavenlinkUser.Unmarshal(m, b)
}
func (m *MavenlinkUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MavenlinkUser.Marshal(b, m, deterministic)
}
func (dst *MavenlinkUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MavenlinkUser.Merge(dst, src)
}
func (m *MavenlinkUser) XXX_Size() int {
	return xxx_messageInfo_MavenlinkUser.Size(m)
}
func (m *MavenlinkUser) XXX_DiscardUnknown() {
	xxx_messageInfo_MavenlinkUser.DiscardUnknown(m)
}

var xxx_messageInfo_MavenlinkUser proto.InternalMessageInfo

func (m *MavenlinkUser) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MavenlinkUser) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *MavenlinkUser) GetPhotoPath() string {
	if m != nil {
		return m.PhotoPath
	}
	return ""
}

func (m *MavenlinkUser) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *MavenlinkUser) GetHeadline() string {
	if m != nil {
		return m.Headline
	}
	return ""
}

func (m *MavenlinkUser) GetGeneric() bool {
	if m != nil {
		return m.Generic
	}
	return false
}

func (m *MavenlinkUser) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *MavenlinkUser) GetUpdateWhitelist() []string {
	if m != nil {
		return m.UpdateWhitelist
	}
	return nil
}

func (m *MavenlinkUser) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type MavenlinkResponseMeta struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	PageCount            int32    `protobuf:"varint,2,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	PageNumber           int32    `protobuf:"varint,3,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	Page_Size            int32    `protobuf:"varint,4,opt,name=page_Size,json=pageSize,proto3" json:"page_Size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MavenlinkResponseMeta) Reset()         { *m = MavenlinkResponseMeta{} }
func (m *MavenlinkResponseMeta) String() string { return proto.CompactTextString(m) }
func (*MavenlinkResponseMeta) ProtoMessage()    {}
func (*MavenlinkResponseMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_mavenlink_communicator_a9af29e9786aea96, []int{9}
}
func (m *MavenlinkResponseMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MavenlinkResponseMeta.Unmarshal(m, b)
}
func (m *MavenlinkResponseMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MavenlinkResponseMeta.Marshal(b, m, deterministic)
}
func (dst *MavenlinkResponseMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MavenlinkResponseMeta.Merge(dst, src)
}
func (m *MavenlinkResponseMeta) XXX_Size() int {
	return xxx_messageInfo_MavenlinkResponseMeta.Size(m)
}
func (m *MavenlinkResponseMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_MavenlinkResponseMeta.DiscardUnknown(m)
}

var xxx_messageInfo_MavenlinkResponseMeta proto.InternalMessageInfo

func (m *MavenlinkResponseMeta) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *MavenlinkResponseMeta) GetPageCount() int32 {
	if m != nil {
		return m.PageCount
	}
	return 0
}

func (m *MavenlinkResponseMeta) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *MavenlinkResponseMeta) GetPage_Size() int32 {
	if m != nil {
		return m.Page_Size
	}
	return 0
}

type MavenlinkWorkspacesResponse struct {
	Count                int32                          `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Meta                 *MavenlinkResponseMeta         `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Results              []*MavenlinkResponseResults    `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	Workspaces           map[string]*MavenlinkWorkspace `protobuf:"bytes,4,rep,name=workspaces,proto3" json:"workspaces,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Stories              map[string]*MavenlinkStory     `protobuf:"bytes,5,rep,name=stories,proto3" json:"stories,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *MavenlinkWorkspacesResponse) Reset()         { *m = MavenlinkWorkspacesResponse{} }
func (m *MavenlinkWorkspacesResponse) String() string { return proto.CompactTextString(m) }
func (*MavenlinkWorkspacesResponse) ProtoMessage()    {}
func (*MavenlinkWorkspacesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_mavenlink_communicator_a9af29e9786aea96, []int{10}
}
func (m *MavenlinkWorkspacesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MavenlinkWorkspacesResponse.Unmarshal(m, b)
}
func (m *MavenlinkWorkspacesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MavenlinkWorkspacesResponse.Marshal(b, m, deterministic)
}
func (dst *MavenlinkWorkspacesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MavenlinkWorkspacesResponse.Merge(dst, src)
}
func (m *MavenlinkWorkspacesResponse) XXX_Size() int {
	return xxx_messageInfo_MavenlinkWorkspacesResponse.Size(m)
}
func (m *MavenlinkWorkspacesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MavenlinkWorkspacesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MavenlinkWorkspacesResponse proto.InternalMessageInfo

func (m *MavenlinkWorkspacesResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *MavenlinkWorkspacesResponse) GetMeta() *MavenlinkResponseMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *MavenlinkWorkspacesResponse) GetResults() []*MavenlinkResponseResults {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *MavenlinkWorkspacesResponse) GetWorkspaces() map[string]*MavenlinkWorkspace {
	if m != nil {
		return m.Workspaces
	}
	return nil
}

func (m *MavenlinkWorkspacesResponse) GetStories() map[string]*MavenlinkStory {
	if m != nil {
		return m.Stories
	}
	return nil
}

type MavenlinkStoriesResponse struct {
	Count                int32                       `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Meta                 *MavenlinkResponseMeta      `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Results              []*MavenlinkResponseResults `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	Stories              map[string]*MavenlinkStory  `protobuf:"bytes,4,rep,name=stories,proto3" json:"stories,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *MavenlinkStoriesResponse) Reset()         { *m = MavenlinkStoriesResponse{} }
func (m *MavenlinkStoriesResponse) String() string { return proto.CompactTextString(m) }
func (*MavenlinkStoriesResponse) ProtoMessage()    {}
func (*MavenlinkStoriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_mavenlink_communicator_a9af29e9786aea96, []int{11}
}
func (m *MavenlinkStoriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MavenlinkStoriesResponse.Unmarshal(m, b)
}
func (m *MavenlinkStoriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MavenlinkStoriesResponse.Marshal(b, m, deterministic)
}
func (dst *MavenlinkStoriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MavenlinkStoriesResponse.Merge(dst, src)
}
func (m *MavenlinkStoriesResponse) XXX_Size() int {
	return xxx_messageInfo_MavenlinkStoriesResponse.Size(m)
}
func (m *MavenlinkStoriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MavenlinkStoriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MavenlinkStoriesResponse proto.InternalMessageInfo

func (m *MavenlinkStoriesResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *MavenlinkStoriesResponse) GetMeta() *MavenlinkResponseMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *MavenlinkStoriesResponse) GetResults() []*MavenlinkResponseResults {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *MavenlinkStoriesResponse) GetStories() map[string]*MavenlinkStory {
	if m != nil {
		return m.Stories
	}
	return nil
}

type MavenlinkTimeEntriesResponse struct {
	Count                int32                          `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Meta                 *MavenlinkResponseMeta         `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Results              []*MavenlinkResponseResults    `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	TimeEntries          map[string]*MavenlinkTimeentry `protobuf:"bytes,4,rep,name=time_entries,json=timeEntries,proto3" json:"time_entries,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *MavenlinkTimeEntriesResponse) Reset()         { *m = MavenlinkTimeEntriesResponse{} }
func (m *MavenlinkTimeEntriesResponse) String() string { return proto.CompactTextString(m) }
func (*MavenlinkTimeEntriesResponse) ProtoMessage()    {}
func (*MavenlinkTimeEntriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_mavenlink_communicator_a9af29e9786aea96, []int{12}
}
func (m *MavenlinkTimeEntriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MavenlinkTimeEntriesResponse.Unmarshal(m, b)
}
func (m *MavenlinkTimeEntriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MavenlinkTimeEntriesResponse.Marshal(b, m, deterministic)
}
func (dst *MavenlinkTimeEntriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MavenlinkTimeEntriesResponse.Merge(dst, src)
}
func (m *MavenlinkTimeEntriesResponse) XXX_Size() int {
	return xxx_messageInfo_MavenlinkTimeEntriesResponse.Size(m)
}
func (m *MavenlinkTimeEntriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MavenlinkTimeEntriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MavenlinkTimeEntriesResponse proto.InternalMessageInfo

func (m *MavenlinkTimeEntriesResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *MavenlinkTimeEntriesResponse) GetMeta() *MavenlinkResponseMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *MavenlinkTimeEntriesResponse) GetResults() []*MavenlinkResponseResults {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *MavenlinkTimeEntriesResponse) GetTimeEntries() map[string]*MavenlinkTimeentry {
	if m != nil {
		return m.TimeEntries
	}
	return nil
}

type MavenlinkUsersResponse struct {
	Count                int32                       `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Meta                 *MavenlinkResponseMeta      `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Results              []*MavenlinkResponseResults `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	Users                map[string]*MavenlinkUser   `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *MavenlinkUsersResponse) Reset()         { *m = MavenlinkUsersResponse{} }
func (m *MavenlinkUsersResponse) String() string { return proto.CompactTextString(m) }
func (*MavenlinkUsersResponse) ProtoMessage()    {}
func (*MavenlinkUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_mavenlink_communicator_a9af29e9786aea96, []int{13}
}
func (m *MavenlinkUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MavenlinkUsersResponse.Unmarshal(m, b)
}
func (m *MavenlinkUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MavenlinkUsersResponse.Marshal(b, m, deterministic)
}
func (dst *MavenlinkUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MavenlinkUsersResponse.Merge(dst, src)
}
func (m *MavenlinkUsersResponse) XXX_Size() int {
	return xxx_messageInfo_MavenlinkUsersResponse.Size(m)
}
func (m *MavenlinkUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MavenlinkUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MavenlinkUsersResponse proto.InternalMessageInfo

func (m *MavenlinkUsersResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *MavenlinkUsersResponse) GetMeta() *MavenlinkResponseMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *MavenlinkUsersResponse) GetResults() []*MavenlinkResponseResults {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *MavenlinkUsersResponse) GetUsers() map[string]*MavenlinkUser {
	if m != nil {
		return m.Users
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_mavenlink_communicator_a9af29e9786aea96, []int{14}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Request struct {
	KeyOrId              string   `protobuf:"bytes,1,opt,name=keyOrId,proto3" json:"keyOrId,omitempty"`
	Workspace            string   `protobuf:"bytes,2,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Task                 string   `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"`
	SubTask              string   `protobuf:"bytes,4,opt,name=subTask,proto3" json:"subTask,omitempty"`
	IssueTask            string   `protobuf:"bytes,5,opt,name=issueTask,proto3" json:"issueTask,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_mavenlink_communicator_a9af29e9786aea96, []int{15}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetKeyOrId() string {
	if m != nil {
		return m.KeyOrId
	}
	return ""
}

func (m *Request) GetWorkspace() string {
	if m != nil {
		return m.Workspace
	}
	return ""
}

func (m *Request) GetTask() string {
	if m != nil {
		return m.Task
	}
	return ""
}

func (m *Request) GetSubTask() string {
	if m != nil {
		return m.SubTask
	}
	return ""
}

func (m *Request) GetIssueTask() string {
	if m != nil {
		return m.IssueTask
	}
	return ""
}

type Response struct {
	Project              *Project     `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Projects             []*Project   `protobuf:"bytes,2,rep,name=projects,proto3" json:"projects,omitempty"`
	Task                 *Task        `protobuf:"bytes,4,opt,name=task,proto3" json:"task,omitempty"`
	Tasks                []*Task      `protobuf:"bytes,5,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Timeentry            *Timeentry   `protobuf:"bytes,6,opt,name=timeentry,proto3" json:"timeentry,omitempty"`
	Timeentries          []*Timeentry `protobuf:"bytes,7,rep,name=timeentries,proto3" json:"timeentries,omitempty"`
	User                 *User        `protobuf:"bytes,8,opt,name=user,proto3" json:"user,omitempty"`
	Users                []*User      `protobuf:"bytes,9,rep,name=users,proto3" json:"users,omitempty"`
	Error                *Error       `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_mavenlink_communicator_a9af29e9786aea96, []int{16}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

func (m *Response) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

func (m *Response) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

func (m *Response) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *Response) GetTimeentry() *Timeentry {
	if m != nil {
		return m.Timeentry
	}
	return nil
}

func (m *Response) GetTimeentries() []*Timeentry {
	if m != nil {
		return m.Timeentries
	}
	return nil
}

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Response) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type EnvironmentConfiguration struct {
	Debug                bool     `protobuf:"varint,1,opt,name=debug,proto3" json:"debug,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnvironmentConfiguration) Reset()         { *m = EnvironmentConfiguration{} }
func (m *EnvironmentConfiguration) String() string { return proto.CompactTextString(m) }
func (*EnvironmentConfiguration) ProtoMessage()    {}
func (*EnvironmentConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_mavenlink_communicator_a9af29e9786aea96, []int{17}
}
func (m *EnvironmentConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvironmentConfiguration.Unmarshal(m, b)
}
func (m *EnvironmentConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvironmentConfiguration.Marshal(b, m, deterministic)
}
func (dst *EnvironmentConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvironmentConfiguration.Merge(dst, src)
}
func (m *EnvironmentConfiguration) XXX_Size() int {
	return xxx_messageInfo_EnvironmentConfiguration.Size(m)
}
func (m *EnvironmentConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvironmentConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_EnvironmentConfiguration proto.InternalMessageInfo

func (m *EnvironmentConfiguration) GetDebug() bool {
	if m != nil {
		return m.Debug
	}
	return false
}

func (m *EnvironmentConfiguration) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *EnvironmentConfiguration) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*Project)(nil), "costrategix.service.mavenlink.communicator.Project")
	proto.RegisterType((*Task)(nil), "costrategix.service.mavenlink.communicator.Task")
	proto.RegisterType((*Timeentry)(nil), "costrategix.service.mavenlink.communicator.Timeentry")
	proto.RegisterType((*User)(nil), "costrategix.service.mavenlink.communicator.User")
	proto.RegisterType((*MavenlinkResponseResults)(nil), "costrategix.service.mavenlink.communicator.MavenlinkResponseResults")
	proto.RegisterType((*MavenlinkWorkspace)(nil), "costrategix.service.mavenlink.communicator.MavenlinkWorkspace")
	proto.RegisterType((*MavenlinkStory)(nil), "costrategix.service.mavenlink.communicator.MavenlinkStory")
	proto.RegisterType((*MavenlinkTimeentry)(nil), "costrategix.service.mavenlink.communicator.MavenlinkTimeentry")
	proto.RegisterType((*MavenlinkUser)(nil), "costrategix.service.mavenlink.communicator.MavenlinkUser")
	proto.RegisterType((*MavenlinkResponseMeta)(nil), "costrategix.service.mavenlink.communicator.MavenlinkResponseMeta")
	proto.RegisterType((*MavenlinkWorkspacesResponse)(nil), "costrategix.service.mavenlink.communicator.MavenlinkWorkspacesResponse")
	proto.RegisterMapType((map[string]*MavenlinkStory)(nil), "costrategix.service.mavenlink.communicator.MavenlinkWorkspacesResponse.StoriesEntry")
	proto.RegisterMapType((map[string]*MavenlinkWorkspace)(nil), "costrategix.service.mavenlink.communicator.MavenlinkWorkspacesResponse.WorkspacesEntry")
	proto.RegisterType((*MavenlinkStoriesResponse)(nil), "costrategix.service.mavenlink.communicator.MavenlinkStoriesResponse")
	proto.RegisterMapType((map[string]*MavenlinkStory)(nil), "costrategix.service.mavenlink.communicator.MavenlinkStoriesResponse.StoriesEntry")
	proto.RegisterType((*MavenlinkTimeEntriesResponse)(nil), "costrategix.service.mavenlink.communicator.MavenlinkTimeEntriesResponse")
	proto.RegisterMapType((map[string]*MavenlinkTimeentry)(nil), "costrategix.service.mavenlink.communicator.MavenlinkTimeEntriesResponse.TimeEntriesEntry")
	proto.RegisterType((*MavenlinkUsersResponse)(nil), "costrategix.service.mavenlink.communicator.MavenlinkUsersResponse")
	proto.RegisterMapType((map[string]*MavenlinkUser)(nil), "costrategix.service.mavenlink.communicator.MavenlinkUsersResponse.UsersEntry")
	proto.RegisterType((*Error)(nil), "costrategix.service.mavenlink.communicator.Error")
	proto.RegisterType((*Request)(nil), "costrategix.service.mavenlink.communicator.Request")
	proto.RegisterType((*Response)(nil), "costrategix.service.mavenlink.communicator.Response")
	proto.RegisterType((*EnvironmentConfiguration)(nil), "costrategix.service.mavenlink.communicator.EnvironmentConfiguration")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for MavenlinkCommunicator service

type MavenlinkCommunicatorClient interface {
	GetAllProjects(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	GetProjectById(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	GetTasksByProjectId(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	GetSubTasksByParentTaskAndProjectId(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	GetTasksBySubTaskParentTaskAndProjectId(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	GetTimeentries(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	GetUsers(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	GetUser(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type mavenlinkCommunicatorClient struct {
	c           client.Client
	serviceName string
}

func NewMavenlinkCommunicatorClient(serviceName string, c client.Client) MavenlinkCommunicatorClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "costrategix.service.mavenlink.communicator"
	}
	return &mavenlinkCommunicatorClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *mavenlinkCommunicatorClient) GetAllProjects(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "MavenlinkCommunicator.GetAllProjects", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mavenlinkCommunicatorClient) GetProjectById(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "MavenlinkCommunicator.GetProjectById", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mavenlinkCommunicatorClient) GetTasksByProjectId(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "MavenlinkCommunicator.GetTasksByProjectId", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mavenlinkCommunicatorClient) GetSubTasksByParentTaskAndProjectId(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "MavenlinkCommunicator.GetSubTasksByParentTaskAndProjectId", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mavenlinkCommunicatorClient) GetTasksBySubTaskParentTaskAndProjectId(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "MavenlinkCommunicator.GetTasksBySubTaskParentTaskAndProjectId", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mavenlinkCommunicatorClient) GetTimeentries(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "MavenlinkCommunicator.GetTimeentries", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mavenlinkCommunicatorClient) GetUsers(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "MavenlinkCommunicator.GetUsers", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mavenlinkCommunicatorClient) GetUser(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "MavenlinkCommunicator.GetUser", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MavenlinkCommunicator service

type MavenlinkCommunicatorHandler interface {
	GetAllProjects(context.Context, *Request, *Response) error
	GetProjectById(context.Context, *Request, *Response) error
	GetTasksByProjectId(context.Context, *Request, *Response) error
	GetSubTasksByParentTaskAndProjectId(context.Context, *Request, *Response) error
	GetTasksBySubTaskParentTaskAndProjectId(context.Context, *Request, *Response) error
	GetTimeentries(context.Context, *Request, *Response) error
	GetUsers(context.Context, *Request, *Response) error
	GetUser(context.Context, *Request, *Response) error
}

func RegisterMavenlinkCommunicatorHandler(s server.Server, hdlr MavenlinkCommunicatorHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&MavenlinkCommunicator{hdlr}, opts...))
}

type MavenlinkCommunicator struct {
	MavenlinkCommunicatorHandler
}

func (h *MavenlinkCommunicator) GetAllProjects(ctx context.Context, in *Request, out *Response) error {
	return h.MavenlinkCommunicatorHandler.GetAllProjects(ctx, in, out)
}

func (h *MavenlinkCommunicator) GetProjectById(ctx context.Context, in *Request, out *Response) error {
	return h.MavenlinkCommunicatorHandler.GetProjectById(ctx, in, out)
}

func (h *MavenlinkCommunicator) GetTasksByProjectId(ctx context.Context, in *Request, out *Response) error {
	return h.MavenlinkCommunicatorHandler.GetTasksByProjectId(ctx, in, out)
}

func (h *MavenlinkCommunicator) GetSubTasksByParentTaskAndProjectId(ctx context.Context, in *Request, out *Response) error {
	return h.MavenlinkCommunicatorHandler.GetSubTasksByParentTaskAndProjectId(ctx, in, out)
}

func (h *MavenlinkCommunicator) GetTasksBySubTaskParentTaskAndProjectId(ctx context.Context, in *Request, out *Response) error {
	return h.MavenlinkCommunicatorHandler.GetTasksBySubTaskParentTaskAndProjectId(ctx, in, out)
}

func (h *MavenlinkCommunicator) GetTimeentries(ctx context.Context, in *Request, out *Response) error {
	return h.MavenlinkCommunicatorHandler.GetTimeentries(ctx, in, out)
}

func (h *MavenlinkCommunicator) GetUsers(ctx context.Context, in *Request, out *Response) error {
	return h.MavenlinkCommunicatorHandler.GetUsers(ctx, in, out)
}

func (h *MavenlinkCommunicator) GetUser(ctx context.Context, in *Request, out *Response) error {
	return h.MavenlinkCommunicatorHandler.GetUser(ctx, in, out)
}

func init() {
	proto.RegisterFile("proto/mavenlink-communicator/mavenlink-communicator.proto", fileDescriptor_mavenlink_communicator_a9af29e9786aea96)
}

var fileDescriptor_mavenlink_communicator_a9af29e9786aea96 = []byte{
	// 1731 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x59, 0x5f, 0x6f, 0x23, 0x49,
	0x11, 0xc7, 0x7f, 0x66, 0x3d, 0x53, 0x76, 0xfe, 0xa8, 0x59, 0x60, 0x2e, 0xbb, 0x2b, 0x72, 0x3e,
	0x71, 0x17, 0x4e, 0x87, 0x81, 0x1c, 0x48, 0xdc, 0x09, 0x90, 0xb2, 0xc9, 0x12, 0x59, 0x22, 0xb7,
	0x61, 0x92, 0xd5, 0xc2, 0x0b, 0xa3, 0xf6, 0x4c, 0x25, 0x69, 0x3c, 0x9e, 0x31, 0xdd, 0x3d, 0x5e,
	0x8c, 0x38, 0x1e, 0x78, 0x44, 0xe2, 0x01, 0x90, 0x78, 0xe2, 0x95, 0xef, 0xc0, 0x0b, 0x3a, 0x89,
	0x47, 0xc4, 0x07, 0xe0, 0x23, 0xc0, 0xb7, 0x40, 0xfd, 0x67, 0xc6, 0x13, 0x3b, 0x9b, 0x3b, 0x3b,
	0x21, 0x77, 0x5a, 0xf1, 0x14, 0xd7, 0xaf, 0xbb, 0xab, 0xaa, 0xeb, 0x57, 0x55, 0xdd, 0xd3, 0x81,
	0xf7, 0xc6, 0x3c, 0x93, 0xd9, 0xd7, 0x47, 0x74, 0x82, 0x69, 0xc2, 0xd2, 0xe1, 0xd7, 0xa2, 0x6c,
	0x34, 0xca, 0x53, 0x16, 0x51, 0x99, 0xf1, 0x97, 0xc0, 0x3d, 0xbd, 0x86, 0xbc, 0x1d, 0x65, 0x42,
	0x72, 0x2a, 0xf1, 0x9c, 0xfd, 0xa2, 0x27, 0x90, 0x4f, 0x58, 0x84, 0xbd, 0x72, 0x45, 0xaf, 0xba,
	0xa2, 0xfb, 0xfb, 0x06, 0xb4, 0x8e, 0x79, 0xf6, 0x33, 0x8c, 0x24, 0x59, 0x87, 0x3a, 0x8b, 0xfd,
	0xda, 0x76, 0x6d, 0xc7, 0x0b, 0xea, 0x2c, 0x26, 0xf7, 0xc1, 0x91, 0x4c, 0x26, 0xe8, 0xd7, 0x35,
	0x64, 0x04, 0xb2, 0x0d, 0xed, 0x18, 0x45, 0xc4, 0xd9, 0x58, 0xb2, 0x2c, 0xf5, 0x1b, 0x7a, 0xac,
	0x0a, 0xa9, 0x19, 0x34, 0x8a, 0x50, 0x88, 0x1f, 0xe2, 0x04, 0x13, 0xbf, 0x69, 0x66, 0x54, 0x20,
	0xf2, 0x10, 0x3c, 0x1a, 0x45, 0x59, 0x9e, 0xca, 0x7e, 0xec, 0x3b, 0xdb, 0xb5, 0x1d, 0x27, 0x98,
	0x01, 0x64, 0x0b, 0x5c, 0xca, 0xa3, 0x0b, 0x36, 0xc1, 0xd8, 0xbf, 0xb7, 0x5d, 0xdb, 0x71, 0x83,
	0x52, 0x56, 0x63, 0x51, 0xce, 0x39, 0xa6, 0xd1, 0xd4, 0x6f, 0x69, 0xc5, 0xa5, 0x4c, 0xde, 0x84,
	0xf5, 0xe2, 0xf7, 0xc9, 0x74, 0x34, 0xc8, 0x12, 0xdf, 0xd5, 0x33, 0xe6, 0x50, 0xe2, 0x43, 0x2b,
	0xce, 0xf1, 0x80, 0x4a, 0xf4, 0x3d, 0x3d, 0xa1, 0x10, 0xc9, 0xdb, 0xb0, 0x89, 0x67, 0x67, 0x18,
	0x49, 0x36, 0xc1, 0x03, 0x3b, 0x05, 0xf4, 0x94, 0x05, 0x5c, 0xed, 0x41, 0x48, 0xca, 0xa5, 0x9e,
	0xd4, 0xd6, 0x93, 0x66, 0x80, 0x1a, 0x8d, 0x38, 0x52, 0x89, 0xf1, 0x9e, 0xf4, 0x3b, 0x66, 0xb4,
	0x04, 0xd4, 0x68, 0x3e, 0x8e, 0xed, 0xe8, 0x9a, 0x19, 0x2d, 0x81, 0xee, 0xbf, 0x1a, 0xd0, 0x3c,
	0xa5, 0x62, 0x78, 0x6b, 0x84, 0x3c, 0x02, 0x10, 0x32, 0xe3, 0xd3, 0x50, 0x4e, 0xc7, 0x68, 0xf9,
	0xf0, 0x34, 0x72, 0x3a, 0x1d, 0xa3, 0x8a, 0xe9, 0x98, 0xb3, 0x8c, 0x33, 0x39, 0xd5, 0x64, 0x78,
	0x41, 0x29, 0x5f, 0xcb, 0xc5, 0xeb, 0xd0, 0x79, 0x91, 0xf1, 0xa1, 0x18, 0xd3, 0x08, 0x43, 0x16,
	0x5b, 0x3e, 0xda, 0x25, 0xd6, 0x8f, 0x95, 0x65, 0xbd, 0xeb, 0x8c, 0xab, 0x09, 0x6e, 0x25, 0x0e,
	0x19, 0xef, 0xc7, 0xe4, 0x01, 0x78, 0x63, 0xca, 0x31, 0x95, 0x6a, 0xd4, 0xb3, 0xa6, 0x35, 0xd0,
	0x8f, 0xc9, 0x6b, 0xe0, 0xc6, 0x39, 0x86, 0xf1, 0x8c, 0x84, 0x92, 0xa7, 0xfb, 0xe0, 0x08, 0x39,
	0x8b, 0xbb, 0x11, 0xcc, 0x36, 0x29, 0x97, 0x66, 0x49, 0x67, 0x9e, 0x92, 0xc2, 0x17, 0x8c, 0x43,
	0x5a, 0x46, 0x7d, 0xc6, 0xc9, 0x23, 0x00, 0x4b, 0x81, 0x1a, 0x5e, 0x9f, 0x23, 0x85, 0x1c, 0x40,
	0x33, 0x17, 0xc8, 0xfd, 0x8d, 0xed, 0xda, 0x4e, 0x7b, 0xf7, 0x1b, 0xbd, 0x4f, 0x5e, 0x63, 0xbd,
	0x67, 0x02, 0x79, 0xa0, 0x57, 0x77, 0xff, 0x5e, 0x07, 0xef, 0x94, 0x8d, 0x10, 0x53, 0xc9, 0xa7,
	0x0b, 0xfc, 0x7e, 0x05, 0xd6, 0x95, 0xb9, 0x70, 0x8c, 0xfc, 0x2c, 0xe3, 0x23, 0x8c, 0x2d, 0xd1,
	0x6b, 0x0a, 0x3d, 0x2e, 0x40, 0xf2, 0x26, 0x6c, 0x48, 0x36, 0xc2, 0x90, 0xa5, 0xe1, 0x88, 0xa5,
	0xb9, 0x44, 0xa1, 0x49, 0x77, 0x82, 0x35, 0x05, 0xf7, 0xd3, 0x23, 0x03, 0xaa, 0x28, 0xa5, 0x99,
	0x1a, 0x35, 0x8c, 0x1b, 0x61, 0x81, 0x35, 0x67, 0x91, 0xb5, 0xd7, 0xc0, 0x35, 0xf9, 0xc2, 0x0c,
	0xe9, 0x5e, 0xd0, 0xd2, 0x72, 0x85, 0x50, 0x13, 0xa5, 0xd6, 0xf5, 0x41, 0x74, 0x5f, 0x16, 0x44,
	0xef, 0x46, 0x41, 0xfc, 0x63, 0x0d, 0x9a, 0x4a, 0x5c, 0x88, 0xdf, 0x03, 0xf0, 0xce, 0xf2, 0x24,
	0x09, 0x53, 0x3a, 0x2a, 0x6a, 0xc4, 0x55, 0xc0, 0x07, 0x74, 0x84, 0xe4, 0x0d, 0x58, 0xc3, 0x11,
	0x65, 0x49, 0x48, 0xe3, 0x98, 0xa3, 0x10, 0xb6, 0x50, 0x3a, 0x1a, 0xdc, 0x33, 0x98, 0x4a, 0xf7,
	0x0b, 0xa4, 0x71, 0xc2, 0xd2, 0xa2, 0x4e, 0x4a, 0x59, 0xed, 0xcd, 0xf6, 0xa8, 0x59, 0xd8, 0x66,
	0x5d, 0xab, 0xfb, 0x5d, 0xf0, 0x8f, 0x0a, 0xd7, 0x03, 0x14, 0xe3, 0x2c, 0x15, 0x18, 0xa0, 0xc8,
	0x13, 0x29, 0xc8, 0x26, 0x34, 0x86, 0x38, 0xb5, 0x9e, 0xaa, 0x9f, 0xd6, 0xf5, 0x7a, 0xe1, 0x7a,
	0xf7, 0x2f, 0x0d, 0x20, 0xe5, 0xf2, 0xe7, 0x05, 0x17, 0xb7, 0xd6, 0x01, 0x5e, 0x87, 0x8e, 0xe9,
	0xbf, 0x61, 0xf2, 0xb2, 0x9e, 0xbc, 0xb8, 0xbd, 0x5b, 0x69, 0xca, 0x6f, 0xc1, 0x46, 0xf1, 0x3b,
	0x14, 0xd7, 0x75, 0xe5, 0x6a, 0xb9, 0xcf, 0xb5, 0xe5, 0x77, 0x80, 0x94, 0xed, 0x37, 0x9c, 0xeb,
	0x09, 0x8b, 0x8d, 0xf9, 0x72, 0x1b, 0x68, 0x5f, 0xdf, 0x06, 0x3a, 0xd7, 0x67, 0xf0, 0x42, 0x6f,
	0xfe, 0xa8, 0x01, 0xeb, 0x25, 0x4f, 0x27, 0xaa, 0x28, 0xfe, 0xdf, 0xa5, 0x3f, 0x43, 0x5d, 0x5a,
	0xe5, 0xb9, 0x10, 0xec, 0x3c, 0x45, 0xb5, 0x57, 0xe1, 0x6f, 0x6c, 0x37, 0x74, 0x9e, 0x5b, 0xac,
	0x1f, 0x8b, 0xee, 0xbf, 0xab, 0x95, 0x76, 0x67, 0xbd, 0xb8, 0x0b, 0x6b, 0xaa, 0xd1, 0xa9, 0x79,
	0x11, 0xa6, 0xd2, 0xf4, 0x64, 0x27, 0x68, 0x2b, 0xb0, 0x9f, 0xee, 0x2b, 0x68, 0xd6, 0xaf, 0x9d,
	0x6a, 0xbf, 0xde, 0x02, 0x77, 0xc0, 0x92, 0x84, 0x0e, 0x12, 0x2c, 0xb8, 0x2d, 0xe4, 0x4f, 0xc2,
	0x6d, 0xb5, 0x97, 0xbb, 0x97, 0x7b, 0x79, 0xb5, 0x6c, 0xbd, 0xb9, 0xb2, 0x7d, 0x07, 0x48, 0x59,
	0xb6, 0x03, 0x2a, 0x30, 0xcc, 0x53, 0x26, 0x35, 0xc1, 0x4e, 0xb0, 0x59, 0x8c, 0x3c, 0xa6, 0x02,
	0x9f, 0xa5, 0x4c, 0xaa, 0xdd, 0xa9, 0xce, 0x1c, 0x46, 0x34, 0x0d, 0x31, 0x66, 0x52, 0x33, 0xee,
	0x06, 0x6d, 0x05, 0xee, 0xd3, 0xf4, 0x49, 0xcc, 0xa4, 0xce, 0xd1, 0xf1, 0x98, 0x67, 0x2a, 0x47,
	0x3b, 0x36, 0x47, 0xad, 0x4c, 0xbe, 0x04, 0x2d, 0xbd, 0x9e, 0xc5, 0x96, 0xf1, 0x7b, 0x4a, 0x5c,
	0x38, 0x6e, 0xd6, 0xaf, 0xcf, 0x86, 0x8d, 0xf9, 0x62, 0xfd, 0x73, 0x1d, 0xd6, 0x4a, 0xaa, 0x97,
	0x3f, 0x31, 0x1e, 0x01, 0x8c, 0x2f, 0x32, 0x99, 0x85, 0x63, 0x2a, 0x2f, 0x6c, 0xc5, 0x7a, 0x1a,
	0x39, 0xa6, 0xf2, 0x62, 0xf1, 0x40, 0x69, 0x7e, 0xcc, 0x81, 0xe2, 0xcc, 0x1d, 0x28, 0x3e, 0xb4,
	0xce, 0x31, 0x45, 0xce, 0x22, 0x4b, 0x6c, 0x21, 0xaa, 0x55, 0x31, 0x13, 0x8a, 0x62, 0xc3, 0xa9,
	0x1b, 0x94, 0x32, 0xf9, 0x2a, 0x6c, 0x9a, 0x1d, 0x86, 0x2f, 0x2e, 0x98, 0xc4, 0x84, 0x09, 0x75,
	0xd0, 0xaa, 0x34, 0xdf, 0x30, 0xf8, 0xf3, 0x02, 0x9e, 0x6b, 0xe9, 0xde, 0xfc, 0x89, 0xf5, 0xdb,
	0x1a, 0x7c, 0x61, 0xe1, 0xc8, 0x3a, 0x42, 0x49, 0x55, 0x26, 0xea, 0x49, 0x3a, 0x52, 0x4e, 0x60,
	0x04, 0x1d, 0x0f, 0x7a, 0x8e, 0xa1, 0x19, 0xaa, 0x9b, 0x13, 0x42, 0x21, 0xfb, 0x7a, 0xf8, 0xcb,
	0xd0, 0xd6, 0xc3, 0x69, 0x3e, 0x1a, 0x20, 0xb7, 0x65, 0xa0, 0x57, 0x7c, 0xa0, 0x11, 0xd3, 0x47,
	0xce, 0x31, 0x3c, 0x61, 0xbf, 0x44, 0x9b, 0xff, 0xae, 0x02, 0x94, 0xdc, 0xfd, 0x87, 0x03, 0x0f,
	0x16, 0x0f, 0x40, 0x51, 0xb8, 0xf5, 0x12, 0x97, 0x9e, 0x41, 0x73, 0x84, 0x92, 0x6a, 0x67, 0xda,
	0xbb, 0x7b, 0xcb, 0x5c, 0x28, 0xae, 0xdc, 0x79, 0xa0, 0xd5, 0x91, 0x9f, 0x42, 0x8b, 0x9b, 0xa3,
	0xdb, 0x6f, 0x6c, 0x37, 0x76, 0xda, 0xbb, 0x07, 0x37, 0xd2, 0x6c, 0xaf, 0x01, 0x41, 0xa1, 0x94,
	0xbc, 0x00, 0x28, 0x6b, 0x54, 0xe5, 0x8d, 0x32, 0xf1, 0x7c, 0x25, 0x13, 0x8b, 0x91, 0xea, 0xcd,
	0xa0, 0x27, 0xaa, 0xb3, 0x05, 0x15, 0x53, 0x24, 0x05, 0x5d, 0xfd, 0x4c, 0x37, 0x19, 0x65, 0xf5,
	0xf4, 0xb6, 0xac, 0x9e, 0x18, 0xb5, 0xc6, 0x64, 0x61, 0x64, 0xeb, 0x43, 0xd8, 0x98, 0x73, 0xe7,
	0x8a, 0xbb, 0xd0, 0x29, 0x38, 0x13, 0x9a, 0xe4, 0x68, 0x59, 0xfc, 0xfe, 0xcd, 0x5c, 0x0a, 0x8c,
	0xb2, 0xf7, 0xeb, 0xdf, 0xa9, 0x6d, 0x4d, 0xa0, 0x53, 0xf5, 0xeb, 0x0a, 0xdb, 0xc7, 0x97, 0x6d,
	0xbf, 0xbf, 0x92, 0x6d, 0x7d, 0x0f, 0xa8, 0xd8, 0xed, 0xfe, 0xb3, 0x51, 0xb9, 0x0c, 0x5a, 0x0f,
	0x5e, 0xcd, 0x4c, 0x1e, 0xce, 0x12, 0xca, 0xa4, 0xf1, 0x8f, 0x56, 0x8e, 0x20, 0xfb, 0xd8, 0x6c,
	0xfa, 0xb4, 0xe8, 0xfc, 0x4f, 0x03, 0x1e, 0x5e, 0xba, 0x32, 0x28, 0xf3, 0xaf, 0x2c, 0xa5, 0xbf,
	0x82, 0x8e, 0xbe, 0xd2, 0xa0, 0xd9, 0xa4, 0xe5, 0xf5, 0x27, 0x2b, 0x19, 0xb9, 0x22, 0x58, 0xbd,
	0x0a, 0x66, 0xf8, 0x6d, 0xcb, 0x19, 0xb2, 0xf5, 0x6b, 0xd8, 0x9c, 0x9f, 0xf0, 0xbf, 0x6a, 0x19,
	0xe5, 0xe5, 0xaf, 0xca, 0xf5, 0x47, 0x0d, 0xf8, 0xe2, 0xa5, 0x3b, 0xc3, 0x2b, 0xca, 0x72, 0x04,
	0x8e, 0xba, 0x63, 0x15, 0xf4, 0x1e, 0xad, 0xa4, 0xfd, 0x52, 0x7c, 0xf4, 0x27, 0xba, 0xa5, 0xd4,
	0xe8, 0xde, 0x12, 0x00, 0x33, 0xf0, 0x0a, 0x1a, 0x9f, 0x5e, 0xa6, 0xf1, 0xbd, 0x95, 0x9d, 0xa8,
	0x32, 0xf8, 0x3d, 0x70, 0x9e, 0x70, 0x9e, 0x71, 0x42, 0xa0, 0x19, 0x65, 0x31, 0x5a, 0xba, 0xf4,
	0xef, 0xf9, 0xcf, 0xb0, 0xfa, 0xc2, 0x67, 0x58, 0xf7, 0x77, 0x35, 0x68, 0x05, 0xf8, 0xf3, 0x1c,
	0x85, 0x54, 0x37, 0xb4, 0x21, 0x4e, 0x9f, 0xf2, 0x7e, 0x71, 0x67, 0x2c, 0x44, 0xf2, 0x10, 0xbc,
	0xf2, 0x58, 0xb5, 0x5a, 0x66, 0x80, 0xb2, 0x2c, 0xa9, 0x18, 0xda, 0x3b, 0xa3, 0xfe, 0xad, 0x74,
	0x89, 0x7c, 0x70, 0xaa, 0xe0, 0xa6, 0xbd, 0x87, 0x1b, 0x51, 0xe9, 0x62, 0x42, 0xe4, 0xa8, 0xc7,
	0xec, 0xbb, 0x42, 0x09, 0x74, 0xff, 0xe6, 0x80, 0x5b, 0xa6, 0xe0, 0x11, 0xb4, 0xc6, 0xe6, 0xb5,
	0x56, 0x3b, 0xd4, 0xde, 0x7d, 0x77, 0x99, 0x90, 0xd9, 0x87, 0xde, 0xa0, 0xd0, 0x41, 0x9e, 0xaa,
	0x6f, 0x4a, 0xfd, 0x53, 0xf8, 0x75, 0x9d, 0x07, 0x2b, 0xe9, 0x2b, 0x95, 0x90, 0x03, 0xbb, 0xf1,
	0xe6, 0xf2, 0x0f, 0x3c, 0x6a, 0xb3, 0x36, 0x54, 0x3f, 0x00, 0x47, 0xfd, 0x2d, 0xee, 0x28, 0xcb,
	0xab, 0x31, 0xcb, 0xc9, 0x09, 0x78, 0xb2, 0xa8, 0x71, 0x7d, 0xc5, 0x6e, 0xef, 0x7e, 0x7b, 0x29,
	0x5d, 0x65, 0x83, 0x98, 0xe9, 0x21, 0xcf, 0xa1, 0x5d, 0x08, 0xaa, 0x3b, 0xb6, 0xb4, 0x8b, 0x2b,
	0xaa, 0xad, 0x6a, 0x2a, 0x1f, 0xc7, 0xdc, 0x9b, 0x3c, 0x8e, 0xa9, 0xd8, 0x99, 0xba, 0xf6, 0x96,
	0x8f, 0x9d, 0xa9, 0x24, 0xbd, 0x9c, 0x1c, 0x82, 0x83, 0xaa, 0x8a, 0xf4, 0x37, 0x5f, 0x7b, 0xf7,
	0x9b, 0xcb, 0xe8, 0xd1, 0xe5, 0x17, 0x98, 0xf5, 0xdd, 0x1f, 0x83, 0xff, 0x24, 0x9d, 0x30, 0x9e,
	0xa5, 0x23, 0x4c, 0xe5, 0x7e, 0x96, 0x9e, 0xb1, 0xf3, 0x9c, 0x53, 0xfd, 0xe4, 0x71, 0x1f, 0x9c,
	0x18, 0x07, 0xf9, 0xb9, 0x4e, 0x66, 0x37, 0x30, 0x82, 0xea, 0x13, 0x39, 0x4f, 0x6c, 0x55, 0xa9,
	0x9f, 0xfa, 0x49, 0x25, 0x1b, 0x62, 0xf1, 0x6c, 0x62, 0x84, 0xdd, 0xbf, 0xba, 0x95, 0xef, 0x97,
	0xfd, 0x8a, 0x03, 0xe4, 0x43, 0x58, 0x3f, 0x44, 0xb9, 0x97, 0x24, 0xc7, 0x45, 0x62, 0x2e, 0x95,
	0xd7, 0xb6, 0xfc, 0xb7, 0xbe, 0xb5, 0xdc, 0x22, 0x53, 0xa3, 0xdd, 0xcf, 0x59, 0xf3, 0xd6, 0xf6,
	0x63, 0xf5, 0xa9, 0x7d, 0xa7, 0xe6, 0x7f, 0x53, 0x83, 0xcf, 0x1f, 0xa2, 0x54, 0x95, 0x20, 0x1e,
	0x4f, 0xad, 0x1b, 0x77, 0xed, 0xc4, 0x1f, 0x6a, 0xf0, 0xc6, 0x21, 0xca, 0x13, 0xd3, 0xe3, 0x94,
	0x1f, 0xfa, 0xc5, 0x48, 0x09, 0x7b, 0x69, 0xfc, 0x29, 0x39, 0xf5, 0xa7, 0x1a, 0xbc, 0x35, 0x8b,
	0x8c, 0xf5, 0xed, 0xb3, 0xe0, 0x98, 0xc9, 0x98, 0xd3, 0x4a, 0x37, 0xb8, 0x53, 0xf3, 0x2f, 0xc0,
	0x3d, 0x44, 0xa9, 0x8f, 0xea, 0xbb, 0x35, 0x3c, 0x81, 0x96, 0x35, 0x7c, 0xa7, 0x76, 0x07, 0xf7,
	0xf4, 0x7f, 0x4a, 0xdf, 0xfd, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x3b, 0x1c, 0xe8, 0x66,
	0x1d, 0x00, 0x00,
}
